Add Update Product API endpoint docs
CorporateRewards/docs-redstone pull request #28
Opened 2021-11-30 10:09 UTC by OttilieWilliams

2021-11-30 15:11 UTC, OttilieWilliams commented
Links https://github.com/CorporateRewards/redstone/issues/1135

2021-11-30 15:57 UTC, rjpaskin requested changes

2021-11-30 15:57 UTC, rjpaskin commented on source/includes/api/products/update_product.md
> +PATCH /api/v2/products/{123} HTTP/1.1
```suggestion
PATCH /api/v2/products/{product_id} HTTP/1.1
```

2021-11-30 15:57 UTC, rjpaskin commented on source/includes/api/products/update_product.md
> +The update product API is available to update product information. This uses the same params as the create product API above.
Link to section for "same params as the create product API"?

2021-12-08 11:27 UTC, rjpaskin requested changes

2021-12-08 11:27 UTC, rjpaskin commented on source/includes/api/products/update_product.md
> +The update product API is available to update product information. This uses the same params as the [Create product API](https://docs.gps.my-rewards.co.uk/#products-create-product) above.
Don't need the full URL here, just the anchor:
```suggestion
The update product API is available to update product information. This uses the same params as the [Create product API](#products-create-product) above.
```

2021-12-08 13:18 UTC, rjpaskin approved these changes

2021-12-10 10:46 UTC, merged