Add params to Update API docs
CorporateRewards/docs-redstone pull request #29
Opened 2022-01-18 16:08 UTC by OttilieWilliams

Connects CorporateRewards/redstone#1135

Instead of pointing to the Create params - there are a few differences:
- Categories cannot be used as a param
- All the params are optional

Also added more detailed API call and response examples.

2022-01-26 13:12 UTC, OttilieWilliams commented
Links https://github.com/CorporateRewards/redstone/issues/1135

2022-02-01 10:11 UTC, rjpaskin requested changes

2022-02-01 10:11 UTC, rjpaskin commented on source/includes/api/products/update_product.md
> +description  | Html (String)  |  Optional - a textual, detailed description of the product can be plain text or marked up in html
Html -> HTML

2022-02-01 10:11 UTC, rjpaskin commented on source/includes/api/products/update_product.md
> +media  | Url (String)  |  Optional - a publicly accessible url for an image (jpg or png). This will be fetched by our system, transcoded and associated with this product as the primary image. This im
Url -> URL

2022-02-04 09:54 UTC, rjpaskin approved these changes

2022-02-04 10:07 UTC, merged